server:
  port: 9001

spring:
  application:
    name: USER-REGISTRATION-SERVICE
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user?currentSchema=user
    username: postgres
    password: postgres